# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gentoo-latest-amd64"
  config.vm.box_url = "https://dl.dropboxusercontent.com/s/qubuaqiizvfpsyx/gentoo-20131024-amd64.box"

  # config.vm.box = "gentoo-latest-amd64-minimal"
  # config.vm.box_url = "https://dl.dropboxusercontent.com/s/mfurnvstqoj8w47/gentoo-20131024-amd64-minimal.box"
  
  # config.vm.box = "gentoo-latest-i686"
  # config.vm.box_url = "https://dl.dropboxusercontent.com/s/xfl63k64zliixid/gentoo-20131029-i686.box"

  # config.vm.box = "gentoo-latest-i686-minimal"
  # config.vm.box_url = "https://dl.dropboxusercontent.com/s/0e23qmbo97wb5x2/gentoo-20131029-i686-minimal.box"

  config.vm.network :forwarded_port, guest: 80, host: 10080, auto_correct: true
  # config.vm.network :forwarded_port, guest: 8080, host: 18080, auto_correct: true
  # config.vm.network :forwarded_port, guest: 5432, host: 15432, auto_correct: true
  # config.vm.network :forwarded_port, guest: 7100, host: 7100, auto_correct: true

  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
end
